apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
spec:
  replicas: 1
  selector:
    matchLabels:
      role: nfs-server
  template:
    metadata:
      labels:
        role: nfs-server
    spec:
      containers:
      - name: nfs-server
        image: k8s.gcr.io/volume-nfs:0.8
        imagePullPolicy: Always
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: "/exports"
            name: mypvc
          # - mountPath: "/data/mysql"
          #   name: mypvc-mysql
      volumes:
          - name: mypvc
            gcePersistentDisk:
              pdName: nfs-disk
              fsType: ext4
        # - name: mypvc
        #   persistentVolumeClaim:
        #     claimName: nfs-pv-provisioning-demo
        # - name: mypvc-mysql
        #   persistentVolumeClaim:
        #     claimName: nfs-pv-provisioning-mysql
